"use strict";
/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.createClient = void 0;
const requests_1 = require("italia-ts-commons/lib/requests");
const function_1 = require("fp-ts/lib/function");
const requestTypes_1 = require("./requestTypes");
function createClient({ baseUrl, 
// tslint:disable-next-line:no-any
fetchApi, withDefaults, basePath = "/" }) {
    const options = {
        baseUrl,
        fetchApi
    };
    const getServerInfoT = {
        method: "get",
        headers: () => ({}),
        response_decoder: requestTypes_1.getServerInfoDefaultDecoder(),
        url: ({}) => `${basePath}/info`,
        query: () => ({})
    };
    const getServerInfo = requests_1.createFetchRequestForApi(getServerInfoT, options);
    return {
        getServerInfo: (withDefaults || function_1.identity)(getServerInfo)
    };
}
exports.createClient = createClient;
//# sourceMappingURL=client.js.map