/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
import * as t from "io-ts";
export declare const ServerInfo: t.ExactC<t.IntersectionC<[t.TypeC<{}>, t.PartialC<{
    version: t.StringC;
}>]>>;
export declare type ServerInfo = t.TypeOf<typeof ServerInfo>;
