"use strict";
/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServerInfo = void 0;
const t = require("io-ts");
// required attributes
const ServerInfoR = t.interface({});
// optional attributes
const ServerInfoO = t.partial({
    version: t.string
});
exports.ServerInfo = t.exact(t.intersection([ServerInfoR, ServerInfoO], "ServerInfo"));
//# sourceMappingURL=ServerInfo.js.map