parameters:
  # Required
  - name: "COMMAND"
    type: string
    default: "upgrade"
  - name: "ENV"
    type: string
    displayName: '(Required) Which environment is involved into deploy.'
  - name: "KUBERNETES_SERVICE_CONN"
    type: string
    displayName: '(Required) Azure devops service connection name.'
  - name: "APP_NAME"
    type: string
    displayName: '(Required) Helm deploy name.'
  - name: "CHART_PATH"
    type: string
    displayName: '(Required) folder path where to find the Chart.yaml file'
  - name: "VALUE_FILE"
    type: string
    displayName: '(Required) values.yaml file path relative to the repository root'
  # Optional
  - name: "WAIT_FOR_EXECUTION"
    type: boolean
    default: true
  - name: "ARGUMENTS"
    type: string
    default: "--timeout 5m0s"
  - name: "APPINSIGHTS_SERVICE_CONN"
    type: string
    default: "none"
  - name: "APPINSIGHTS_RESOURCE_ID"
    type: string
    default: "none"
  - name: "OVERRIDE_EXTENDS" # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/helm-deploy-v0?view=azure-pipelines
    type: string
    default: ""
    displayName: ",key1=val1,key2=val2"

stages:
#
# SETUP
#
  - stage: set_variables
    displayName: 🔦 ${{parameters.ENV}} set variables ${{parameters.APP_NAME}}
    dependsOn: [ ]
    condition: succeeded()
    jobs:
      - job: set_variable_job
        displayName: Set variable for ${{parameters.APP_NAME}} on ${{parameters.ENV}}
        timeoutInMinutes: $[variables.TIME_OUT]
        steps:
          - checkout: self
          - task: Bash@3
            displayName: 'Set namespace variables'
            name: vars
            inputs:
              targetType: 'inline'
              script: |
                echo "##vso[task.setvariable variable=namespace;isOutput=true]$(yq '.microservice-chart.namespace' $(Build.Repository.LocalPath)/${{parameters.VALUE_FILE}} )"
                echo "##vso[task.setvariable variable=deployversion;isOutput=true]$(yq '.microservice-chart.image.tag' $(Build.Repository.LocalPath)/${{parameters.VALUE_FILE}} )"
                echo "##vso[task.setvariable variable=helmreleasename;isOutput=true]$(yq '.name' $(Build.Repository.LocalPath)/${{parameters.CHART_PATH}}/Chart.yaml )"
          - task: Bash@3
            displayName: 'Print namespace variables'
            inputs:
              targetType: 'inline'
              script: |
                echo "namespace: $(vars.namespace)"
                echo "deployversion: $(vars.deployversion)"
                echo "helmreleasename: $(vars.helmreleasename)"

#
# TEMPLATE
#
  - stage: helm_template
    displayName: 🔦 ${{parameters.ENV}} helm setup ${{parameters.APP_NAME}}
    dependsOn: [set_variables]
    condition: succeeded()
    jobs:
      - job: ${{parameters.ENV}}_template_${{ replace(parameters.APP_NAME, '-', '_') }}
        displayName: "Helm template for ${{parameters.APP_NAME}} on ${{parameters.ENV}}"
        variables:
          namespace: $[stageDependencies.set_variables.set_variable_job.outputs['vars.namespace']]
          deployversion: $[stageDependencies.set_variables.set_variable_job.outputs['vars.deployversion']]
        timeoutInMinutes: $[variables.TIME_OUT]
        steps:
          - checkout: self
          # 1. Setup helm
          - template: ../helm-microservice-chart-setup/template.yaml
            parameters:
              DEPLOY_VERSION: $(deployversion)
              HELM_DEPENDECIES_COMMAND: 'build'
              CHART_FILE: ${{ parameters.CHART_PATH }}
              VALUES_FILE: ${{ parameters.VALUE_FILE }}
#
# DEPLOY
#
  - stage: helm_deploy
    displayName: 🚀 ${{parameters.ENV}} helm deploy ${{parameters.APP_NAME}}
    dependsOn: [helm_template, set_variables]
    condition: succeeded()
    jobs:
      - deployment: ${{parameters.ENV}}_deploy_${{ replace(parameters.APP_NAME, '-', '_') }}
        displayName: "Helm deploy of ${{parameters.APP_NAME}} on ${{parameters.ENV}}"
        timeoutInMinutes: $[variables.TIME_OUT]
        variables:
          namespace: $[stageDependencies.set_variables.set_variable_job.outputs['vars.namespace']]
          deployversion: $[stageDependencies.set_variables.set_variable_job.outputs['vars.deployversion']]
          helmreleasename: $[stageDependencies.set_variables.set_variable_job.outputs['vars.helmreleasename']]
        continueOnError: false
        environment: ${{parameters.ENV}}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../helm-microservice-chart-setup/template.yaml
                  parameters:
                    DEPLOY_VERSION: $(deployversion)
                    HELM_DEPENDECIES_COMMAND: 'build'
                    CHART_FILE: ${{ parameters.CHART_PATH }}
                # 1. deploy helm
                - template: ../helm-microservice-chart-deploy/template.yaml
                  parameters:
                    DO_DEPLOY : true
                    COMMAND: ${{parameters.COMMAND}}
                    ENV: ${{parameters.ENV}}
                    KUBERNETES_SERVICE_CONN: ${{parameters.KUBERNETES_SERVICE_CONN}}
                    NAMESPACE: $(namespace)
                    APP_NAME: $(helmreleasename)
                    CHART_TYPE: "filepath"
                    CHART_PATH: ${{ parameters.CHART_PATH }}
                    VALUE_FILE: ${{ parameters.VALUE_FILE }}
                    DEPLOY_VERSION: $(deployversion)
                    WAIT_FOR_EXECUTION: ${{parameters.WAIT_FOR_EXECUTION}}
                    ARGUMENTS: ${{parameters.ARGUMENTS}}
                    APPINSIGHTS_SERVICE_CONN: ${{parameters.APPINSIGHTS_SERVICE_CONN}}
                    APPINSIGHTS_RESOURCE_ID: ${{parameters.APPINSIGHTS_RESOURCE_ID}}
                    OVERRIDE_EXTENDS: ${{parameters.OVERRIDE_EXTENDS}}
