# Azure DevOps pipeline to do periodic checks

# A pipeline with no CI trigger, just schedules
trigger: none
pr: none

# schedules:
#   - cron: "0/5 * * * *"
#     displayName: Daily midnight yarn.lock upgrade
#     branches:
#       include:
#       - master
#       - yarn-lockfile-upgrade-template
#     always: true # Run always irrespective of changes


# Execute agents (jobs) on latest Ubuntu version.
# To change OS for a specific, ovverride "pool" attribute inside the job definition
pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '10.14.1'
  system.debug: true
  



jobs:
  - job: do_yarn_lock_upgrade   
    steps:
    - template: ../../templates/yarn-lock-upgrade/template.yaml
      parameters:
        projectDir: .devops/__tests__/sample-yarn-upgrade

    - script: |
        GITHUB_TOKEN=$(GITHUB_TOKEN)
        hub pr list | grep "\[Yarn.lock Upgrade]" | awk '{print $1}' | sed 's/#//'
      
      displayName: 'it should open a PR'
