# Azure DevOps pipeline to do periodic checks

# A pipeline with no CI trigger, just schedules
trigger: none
pr: none

# schedules:
#   - cron: "0/5 * * * *"
#     displayName: Daily midnight yarn.lock upgrade
#     branches:
#       include:
#       - master
#       - yarn-lockfile-upgrade-template
#     always: true # Run always irrespective of changes


# Execute agents (jobs) on latest Ubuntu version.
# To change OS for a specific, ovverride "pool" attribute inside the job definition
pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '10.14.1'
  system.debug: true
  



jobs:
  - job: do_yarn_lock_upgrade   
    steps:
    - template: ../../templates/yarn-lock-upgrade/template.yaml
      parameters:
        projectDir: .devops/__tests__/sample-yarn-upgrade


    # setup git author
    - script: |
        #setup hub CLI
        echo "github.com: 
        - user: $GITHUB_USERNAME
          oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub

      displayName: 'Git setup' 

    - script: |
        PR_NUMBER=`hub pr list | grep "\[Yarn.lock Upgrade]" | awk '{print $1}' | sed 's/#//'`

        echo "##vso[task.setvariable variable=pr_number]$PR_NUMBER"

        echo "==> PR $PR_NUMBER"
        if [[ -n "$PR_NUMBER" ]]; then exit 0; else echo "PR Not Found"; exit 1; fi

      displayName: 'it should open a PR'
  
  
    - script: |
        hub issue update $(pr_number) -s closed   
        echo "" > ~/.config/hub
      displayName: Cleanup