# Run terraform init and terraform plan
parameters:
  - name: 'FULL_DOMAIN_NAME'
    displayName: '(Required) Full Domain name. E.g. rtd_app || rtd_common'
    type: string
  - name: 'AZURE_DEVOPS_POOL_AGENT_NAME'
    displayName: '(Required) Azure devops agent name.'
    type: string
  - name: 'AZURE_SERVICE_CONNECTION_PLAN_NAME'
    displayName: '(Required) Azure service connection name for plan.'
    type: string
  - name: 'AZURE_SERVICE_CONNECTION_APPLY_NAME'
    displayName: '(Required) Azure service connection name for apply.'
    type: string
  - name: 'ENVIRONMENT'
    displayName: '(Required) Azure devops ENV name. For example [dev|uat|prod] etc.'
    type: string
  - name: 'TF_ENVIRONMENT_FOLDER'
    displayName: '(Required) Terraform environment folder name to apply to. For example [dev|weudev|uat|weuuat|prod|weuprod] etc.'
    type: string
  - name: 'WORKINGDIR'
    displayName: '(Optional) Working direcory containing terraform templates and the terraform.sh helper.'
    type: string
    default: "src"
  - name: 'AKS_NAME'
    displayName: '(Optional) AKS Name'
    type: string
    default: ""
  - name: 'AKS_API_SERVER_URL'
    displayName: '(Optional) AKS api server url like (e.g. https://my-url.com:443)'
    type: string
    default: ""
  - name: 'AKS_AZURE_DEVOPS_SA_CA_CRT'
    displayName: '(Optional) AKS service account CA cert, used by azure devops account'
    type: string
    default: ""
  - name: 'AKS_AZURE_DEVOPS_SA_TOKEN'
    displayName: '(Optional) AKS service account token, used by azure devops account'
    type: string
    default: ""
  - name: TF_SUMMARIZE
    displayName: Show summarize data
    type: boolean
    default: true

stages:
#
# PLAN
#
  - stage: ${{parameters.ENVIRONMENT}}_plan_apply_${{parameters.FULL_DOMAIN_NAME}}
    displayName: 🔦 ${{parameters.ENVIRONMENT}}_plan_apply_${{parameters.FULL_DOMAIN_NAME}}
    dependsOn: []
    condition: succeeded()
    pool:
      name: ${{parameters.AZURE_DEVOPS_POOL_AGENT_NAME}}
    jobs:
      - job: ${{parameters.ENVIRONMENT}}_plan_${{parameters.FULL_DOMAIN_NAME}}
        timeoutInMinutes: $[variables.TIME_OUT]
        steps:
          - checkout: self
          # 1. Install terraform
          - template: ../terraform-setup/template.yaml@terraform
          - template: ../terraform-summarize/template.yaml@terraform
          # 2. Run terraform plan
          - template: ../terraform-plan/template.yaml@terraform
            parameters:
              AZURE_SERVICE_CONNECTION_NAME: ${{parameters.AZURE_SERVICE_CONNECTION_PLAN_NAME}}
              TF_ENVIRONMENT_FOLDER: ${{parameters.TF_ENVIRONMENT_FOLDER}}
              WORKINGDIR: ${{parameters.WORKINGDIR}}
              AKS_NAME: ${{parameters.AKS_NAME}}
              AKS_API_SERVER_URL: ${{parameters.AKS_API_SERVER_URL}}
              AKS_AZURE_DEVOPS_SA_CA_CRT: ${{parameters.AKS_AZURE_DEVOPS_SA_CA_CRT}}
              AKS_AZURE_DEVOPS_SA_TOKEN: ${{parameters.AKS_AZURE_DEVOPS_SA_TOKEN}}
              TF_SUMMARIZE: ${{parameters.TF_SUMMARIZE}}
      - deployment: ${{parameters.ENVIRONMENT}}_apply_${{parameters.FULL_DOMAIN_NAME}}
        continueOnError: false
        environment: ${{parameters.ENVIRONMENT}}
        strategy:
          runOnce:
            deploy:
              steps:
                # 2. Run terraform apply
                - template: ../terraform-apply/template.yaml@terraform
                  parameters:
                    AZURE_PLAN_SERVICE_CONNECTION_NAME: ${{parameters.AZURE_SERVICE_CONNECTION_PLAN_NAME}}
                    AZURE_APPLY_SERVICE_CONNECTION_NAME: ${{parameters.AZURE_SERVICE_CONNECTION_APPLY_NAME}}
                    WORKINGDIR: ${{parameters.WORKINGDIR}}
                    TF_ENVIRONMENT_FOLDER: ${{parameters.TF_ENVIRONMENT_FOLDER}}
                    AKS_NAME: ${{parameters.AKS_NAME}}
                    AKS_API_SERVER_URL: ${{parameters.AKS_API_SERVER_URL}}
                    AKS_AZURE_DEVOPS_SA_CA_CRT: ${{parameters.AKS_AZURE_DEVOPS_SA_CA_CRT}}
                    AKS_AZURE_DEVOPS_SA_TOKEN: ${{parameters.AKS_AZURE_DEVOPS_SA_TOKEN}}
##
## APPLY
##
#  - stage: ${{parameters.ENVIRONMENT}}_apply_${{parameters.FULL_DOMAIN_NAME}}
#    displayName: 🚀 ${{parameters.ENVIRONMENT}}_apply_${{parameters.FULL_DOMAIN_NAME}}
#    dependsOn: ['${{parameters.ENVIRONMENT}}_plan_${{parameters.FULL_DOMAIN_NAME}}']
#    condition: succeeded()
#    pool:
#      name: ${{parameters.AZURE_DEVOPS_POOL_AGENT_NAME}}
#    jobs:

