# Track an availability event
parameters:
  - name: "APP_INSIGHT_CONNECTION_STRING"
    displayName: "(Required) Application insight connection string"
    type: string
  - name: "PIPELINE_NAME"
    displayName: "(Required) Pipeline name"
    type: string
  - name: "ENVIRONMENT"
    displayName: "(Required) Environment name"
    type: string
  - name: "SUCCESS"
    displayName: "(Required) Environment name"
    type: string
    default: "false"

jobs:
- job: availability
  condition: always()
  strategy:
    parallel: 1
  steps:
    - task: UseNode@1
      inputs:
        version: '23.x'
      displayName: 'Install Node.js'

    - task: Bash@3
      displayName: 'Publish true availability event'
      condition: succeeded()
      inputs:
        targetType: inline
        script: |
          #!/bin/bash
          curl -o availability-publisher.js 'https://raw.githubusercontent.com/pagopa/azure-pipeline-templates/refs/heads/availability-publisher/templates/availability-publisher/availability-publisher.js'
          npm install applicationinsights@2.9.1
          echo "publishing availability event for ${{ parameters.PIPELINE_NAME }} on env ${{ parameters.ENVIRONMENT }} with status ${{ parameters.SUCCESS }}"
          node ./availability-publisher.js
      env:
        APP_INSIGHT_CONNECTION_STRING: ${{ parameters.APP_INSIGHT_CONNECTION_STRING }}
        PIPELINE_NAME: ${{ parameters.PIPELINE_NAME }}
        ENVIRONMENT: ${{ parameters.ENVIRONMENT }}
        SUCCESS: true #${{ parameters.SUCCESS }}

    - task: Bash@3
      displayName: 'Publish false availability event'
      condition: failed()
      inputs:
        targetType: inline
        script: |
          #!/bin/bash
          curl -o availability-publisher.js 'https://raw.githubusercontent.com/pagopa/azure-pipeline-templates/refs/heads/availability-publisher/templates/availability-publisher/availability-publisher.js'
          npm install applicationinsights@2.9.1
          echo "publishing availability event for ${{ parameters.PIPELINE_NAME }} on env ${{ parameters.ENVIRONMENT }} with status ${{ parameters.SUCCESS }}"
          node ./availability-publisher.js
      env:
        APP_INSIGHT_CONNECTION_STRING: ${{ parameters.APP_INSIGHT_CONNECTION_STRING }}
        PIPELINE_NAME: ${{ parameters.PIPELINE_NAME }}
        ENVIRONMENT: ${{ parameters.ENVIRONMENT }}
        SUCCESS: false #${{ parameters.SUCCESS }}


